defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%B %d, %Y %R %p"
    categories: "news"
    comments:   false

exclude:
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Gemfile
- Gemfile.lock
- LICENSE
- new_post.sh
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- site
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

name: "Lite XL"
url: "https://lite-xl.github.io"
permalink: pretty
description: "Lite XL Website"
spdx_license_id: "Apache-2.0"

repository:
  plugins:
    url: "https://github.com/lite-xl/lite-plugins"

locale:
  default: "en"

authors:
  content: "redtide"
  web: "redtide"

kbd:
  use_modifier_symbols: false
  use_key_symbols: true
  use_plus_sign: false
